#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page
# that contains the string Ceci n'est pas une page.
# Requirements:
# The page must return an HTTP 404 error code
# The page must contain the string Ceci n'est pas une page
# Using what you did with 3-redirection, write 4-not_found_page_404
# so that it configures a brand new Ubuntu machine
# to the requirements asked in this task
sudo apt update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo sed -i '/listen 80 default_server/a \\trewrite ^/redirect_me github.com/jbocane6 permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/error404.html
sudo sed -i '/listen 80 default_server/a \\terror_page 404 /error404.html;\nlocation =  /error404.html {\n\troot /var/www/html/;\n\tinternal;\n}' /etc/nginx/sites-available/default
NAME=$(hostname)
sed -i '/listen 80 default_server/a add_header X-Served-By '$NAME';' /etc/nginx/sites-available/default
sudo service nginx restart
