#!/usr/bin/env bash
# This script displays "bad luck from China" on loop 4.
# "bad luck from Japan" on loop 9.
# "bad luck from Italy on loop 17.
# Also displays a counter from 1 to 20 on every line.

i=1

while ((i <= 20))
do
    case $i in
	4)
	    echo -e "$i\nbad luck from China" ;;
	9)
	    echo -e "$i\nbad luck from Japan" ;;
	17)
	    echo -e "$i\nbad luck from Italy" ;;
	*)
	    echo $i ;;
    esac
    ((i++))
done