#!/usr/bin/env bash
# This script displays a counter for hours and minutes
# up to 12 hours

i=0

while ((i <= 12))
do
    echo "Hour: $i"
    j=1
    while ((j <= 59))
    do
	echo $j
	((j++))
    done
    ((i++))
done
